### ISSUE TITLE
不知道是不是pug报错，请求解答

### ISSUE THREAD

**Issue by TY10909** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#1]
我测试了一下，不知道为什么啊，报错了，pug什么的安装了，然后报了个wordcount插件的错，5个error，然后安装完wordcount后还有一个保错，好像是pug的问题
![Snipaste_2023-02-10_20-24-48](https://user-images.githubusercontent.com/112875745/218092420-fc48a0af-5ecc-4593-861e-18c214261780.png)
![Snipaste_2023-02-10_20-23-48](https://user-images.githubusercontent.com/112875745/218092428-9fd374f5-3614-4821-8bad-d6a97047e199.png)

**Comment by sshi-Yu** [comment]
我也遇到了同样的问题，求解答

**Comment by TY10909** [comment]
哥们，加群
qq：649565726

**Comment by TY10909** [comment]
npm install --save hexo-tag-aplayer
npm install hexo-wordcount --save
然后新建essay文件，index.md
添加如下内容
---
title: 即刻短文
date: 2020-07-22 22:06:17
comments: true
aside: false
top_img: false
type: essay
---

**Comment by timigomen** [comment]
请仔细查看文档内容！

**Comment by sshi-Yu** [comment]
文档已更新？
