### ISSUE TITLE
关于404

### ISSUE THREAD

**Issue by OPMonday** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#23]
导航栏文库删不掉，首页位置有问题
![image](https://user-images.githubusercontent.com/105340869/220549074-712d2989-54a3-4b73-acd0-f00d6434f5c1.png)
关于一打开就404
![image](https://user-images.githubusercontent.com/105340869/220549150-3b6c17c9-e7cb-4733-93fe-546f46a3c85f.png)

**Comment by timigomen** [comment]
有么？我去问问

**Comment by timigomen** [comment]
您好，目前我们未测试到有此问题，但是如果后面发现了，我们会尽快修复
