### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Ezgx** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#32]
![image](https://user-images.githubusercontent.com/110729988/224456834-97c6437f-1438-44fc-b0cf-b5eda79f358d.png)
修一下这个

**Comment by timigomen** [comment]
Thank you for your feedback. We will repair it as soon as possible. If necessary, please add a user communication group, group number 649565726

**Comment by timigomen** [comment]
It has been repaired but not optimized. It is recommended to update v0.0.2
