### ISSUE TITLE
【稳定版】导航栏卡卡卡卡卡卡卡卡卡卡卡卡

### ISSUE THREAD

**Issue by RicharPao** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#35]
导航栏在页面滚动时会根据滚动方向切换成页面标题/页面导航 但这个动画是真的卡卡卡卡卡卡卡卡卡卡卡卡
有时候还会两个都蹦出来，直接叠在一起了
有时候导航栏的背景直接没啦！？

**Comment by timigomen** [comment]
已经在对部分代码进行重构了
