### ISSUE TITLE
【测试版】中控台大部分功能无法使用

### ISSUE THREAD

**Issue by RicharPao** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#36]
中控台内的 **暗黑模式 无障碍工具栏 音乐开关** 无法使用

**热评** 开关是否可用未知，因为我没有使用评论

![image](https://user-images.githubusercontent.com/99643174/226078343-3b93a811-b1ef-430f-9315-cda00c6dead2.png)

**Comment by timigomen** [comment]
暂未配置中控台，未适配中控台的按钮

**Comment by RicharPao** [comment]
> 暂未配置中控台，未适配中控台的按钮
