### ISSUE TITLE
【测试版】导航栏背景色消失

### ISSUE THREAD

**Issue by RicharPao** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#37]
从页面顶部向下滚动的时候导航栏的背景色会消失
![image](https://user-images.githubusercontent.com/99643174/226078888-a2eafe5d-646c-4d03-a1ad-4a1ff4c9e1e3.png)

导航栏上链接与页面标题切换的动画也有一些问题，页面标题是突然出现的，所以会这样
![image](https://user-images.githubusercontent.com/99643174/226079184-68939e91-e387-455b-9483-c0bd7a8a13d4.png)

**Comment by MarcusYYDS** [comment]
已准备重写导航栏，感谢反顾

**Comment by MarcusYYDS** [comment]
已解决
