### ISSUE TITLE
评论框小图标好像只有文章页生效，其他被遮挡了！

### ISSUE THREAD

**Issue by fxm0402** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#39]
![image](https://user-images.githubusercontent.com/70627786/228422617-a80d13e4-633b-4cab-b23a-271898860a55.png)
（不着急，不着急，也可以不处理，就是看到了说一下！）感谢大佬开源！

**Comment by anzhiyu-c** [comment]
已修复。
