### ISSUE TITLE
promote版会和next版同步更新吗

### ISSUE THREAD

**Issue by Ezgx** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#45]

**Comment by timigomen** [comment]
先要知道，我們和next斌不是同一個語言，next的開發進度會更快一些，不過未來pug會更好上手，所有btf的魔改教程都可以適配！

**Comment by RicharPao** [comment]
promote是什么版本？new_dev吗，使用方式和普通的一样吗？

**Comment by MarcusYYDS** [comment]
> promote是什么版本？new_dev吗，使用方式和普通的一样吗？

promote预计在51节发布，目前还有一点问题
