### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xiatianPE** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#50]
报错内容，造成无法显示的页面
TypeError: /home/runner/work/www/www/themes/Acrylic/layout/includes/widget/index.pug:19

**Comment by MarcusYYDS** [comment]
请给出截图和log

**Comment by Aaron-zsy** [comment]
![{D8687C71-A121-4df2-8D1D-08E71C9B5C96}](https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic/assets/122505440/2ecbae0b-f949-4318-844c-8809f77ae88a)
请问这个如何解决，谢谢

**Comment by Marcus-zh** [comment]
看样子是footer_friend_link.js的问题,注释掉footer_friend_link.js,然后关闭配置中的footer的friend_link选项,最近几天将会修复

**Comment by Marcus-zh** [comment]
或者可能是没有link.yml,参考https://butterfly.js.org/posts/dc584b87/?highlight=%E5%8F%8B#%E5%8F%8B%E6%83%85%E9%8F%88%E6%8E%A5%E6%B7%BB%E5%8A%A0
