### ISSUE TITLE
hexo server 无法启动

### ISSUE THREAD

**Issue by spldmanager** [hexo-theme-Acrylic/Hexo-Theme-Acrylic#68]
用的是hexo7, hexo6也试过了，运行hexo server后，报多个错误，均类似于
ERROR Script load failed: themes/Acrylic/scripts/events/ajs.js
TypeError: require(...) is not a function

请问如何解决，谢谢

**Comment by spldmanager** [comment]
已解决，需要进入的themes/Acrylic，然后运行npm install ，把两个依赖安装上才行
在hexo的根目录运行npm install 安装是无效的

**Comment by gtwxxh666** [comment]
群内有出现此问题已采纳，谢谢
